"use strict";
const // CONST TIME

	SECOND_MILL = 1000,
	MINUTE_SECOND = 60,
	HOUR_MINUTE = 60,
	HOUR_SECOND = HOUR_MINUTE * HOUR_MINUTE, 
	HOUR_MILL_TIME = HOUR_SECOND * SECOND_MILL,
	AM_TIME_HOUR = 10,
	WORK_TIME = 8,
	WORK_FULL_TIME = WORK_TIME * HOUR_SECOND,
	WORK_MILL_TIME = WORK_TIME * HOUR_MILL_TIME,
	WORK_REIMBURSE_TIME = 10,
	
	FRIDAY = 5,
	
	//WORK
	WORK_START_DATE = 26,
	WORK_END_DATE = 25,
	
	//HTTP STATUS
	SUCCESS_READY_STATE = 4,
	SUCCESS = 200,
	// MONTH
	MONTH = 4,
	HTTP = "http:",
	HTTPS = "https:",
	
	//AJAX TYPE
	POST = "POST", 
	GET = "GET",
	
	// ELEMENT CLASS
	GO_TO_MONTH_CLASS_TYPE = "table.TextCalendar td a",
	GO_TO_MONTH_WORK_TIME_CLASS_TYPE="td.TextCalendar a",
	WORK_TIME_CLASS=".Text0",
	
	// ELEMENT ID
	EVENT_TARGET = "#__EVENTTARGET",
	EVENT_ARGUMENT = "#__EVENTARGUMENT",
	
	//REGX
	REGX_LEFT='(',
	REGX_RIGHT=')',
	REGX_EXPRESSION=/\W{3}/g,
	
	//URL
	URL = "http://gold/attendance/attendance.aspx",
	CONTENT_TYPE="Content-Type",
	CONTENT_TYPE_HEADER="application/x-www-form-urlencoded",
	// STRING
	NULL = "",
	CURRENT_WEEK_LACK_WORK_TIMES = "Current Week Lack Work Times",
	REIMBURSE_WORK_TIMES = "Reimburse Work Times",
	OVER_TIME_WORK_TIMES = "Over Time Work Times"
	;